- python/shotgun_model/shotgunmodel.py
Makes generate_display_name protected rather than private so it can be overridden by a subclass!
> Makes generate_display_name method protected rather than private.

- python/shotgun_model/shotgunmodel.py
Adds a property "entity_ids" which will return a list containing all of the entity_ids currently in the model.
Adds a method "index_from_entity" which returns a QModelIndex for the QStandardItem found that matches the entity_type and entity_id.  If a QStandardItem is not found, None is returned.
Thanks!
> Adds entity_ids property and index_from_entity method.

- docs/shotgun_data.rst
Sample code is wrong.
<pre>
self.__sg_data_retriever.start()
</pre>
should be:
<pre>
self.__sg_data.start()
</pre>
according to the rest of the code.
> Fixed sample code for the documentation on the data retriever

- python/shotgun_globals/__init__.py
- python/shotgun_globals/cached_schema.py
Adds two methods needed to support building a Shotgun field menu.  One to get all the fields for a given entity and another to get the entity types a given entity or multi-entity field can link to.
> Ticket #34755 - Support for building a fields menu

- info.yml
- python/shotgun_globals/__init__.py
- python/shotgun_globals/date_time.py
- python/shotgun_model/shotgun_model.py
- python/shotgun_model/simple_shotgun_model.py
ShotgunModel and SimpleShotgunModel now accept an optional additional_filter_presets argument that is passed down to any API find calls that are run under the hood. If used, it is also incorporated into the caching mechanism's hashing routine.
> Adds support for additional_filter_presets to the ShotgunModel.

- python/settings/user_settings.py
Switched from using `bundle.shotgun.base_url` to `bundle.sgtk.shotgun_url` which prevents a shotgun connection from being created. This helps apps which pull settings at startup - the current code effectively forces such startup code to connect to shotgun, effectively resulting in a slow startup.
> #36875 removed depdenency on shotgun connection

- python/shotgun_globals/cached_schema.py
Fixes minor typo in the variable referencing.
@thebeeland, if you could double check that would be great.
One question I had while looking at the code - the only time we seem to be calling `_load_cached_status()` is from the constructor:
```python
self._load_cached_schema()
self._load_cached_status()
```
So where is the project_id actually being used? Apologies in advance if i am missing something obvious :)
> #37481 Fixed variable reference typo

- python/shotgun_data/shotgun_data_retriever.py
Removed hard-coded '.jpeg' extension for downloaded thumbnails. Let sgtk.util.downolad_url() determine the file extension from the (possibly redirected) url.
> For #40080, support non- .jpeg thumbnail filetypes

- python/shotgun_model/shotgun_hierarchy_item.py
- python/shotgun_model/shotgun_hierarchy_model.py
- python/shotgun_model/simple_shotgun_hierarchy_model.py
A client attempted to use the new API with an unsupported seed. This cleans up the docs to make the limitations clearer. Also hides the `NAV_ENTRIES` additional filter type from the docs to prevent direct usage until it is officially public.
> Doc tweaks for hierarchy model limitations.

- docs/shotgun_hierarchy_model.rst
- info.yml
- python/shotgun_data/shotgun_data_retriever.py
- python/shotgun_model/shotgun_hierarchy_model.py
- python/shotgun_model/simple_shotgun_hierarchy_model.py
- Adds data retriever support for nav search methods
- Adds async expansion/fetch_more methods to the hierarchy model via the async_item_from_entity() and async_item_from_paths () methods.
- upgrades to 0.18 logging
- the hierarchy model _load_data method has a breaking interface change (note: it's not officially released yet). Previously, it would take a path argument, now it takes a root argument instead in order to avoid using path strings to drive the API.
> #42432 Hierarchy search and expansion utils

- python/shotgun_model/shotgun_hierarchy_model.py
- python/task_manager/background_task_manager.py
- python/task_manager/worker_thread.py
- python/utils/__init__.py
- python/utils/qt.py
We're seeing a lot of problems related to garbage collection in PySide2/Qt5 when deleteLater is used. These issues result in crashes on DCC close in some cases, but also errors on app close even when the DCC isn't being closed.
> For #40555: Only uses deleteLater if we're in Qt4.

- python/shotgun_model/shotgun_query_model.py
The fix employed here comes from the Python bug report and appears to resolve the issue entirely. Linked is the stackoverflow that provides more information and links back to the original Python bug ticket.
> For #44161: Works around a thread safety issue with the datetime module.

- python/shotgun_data/shotgun_data_retriever.py
- python/shotgun_model/shotgun_hierarchy_model.py
- python/shotgun_model/shotgun_model.py
Allow to share data cache location for thumbnails and SG queries.
Check if the`Bundle.site_cache_location` which was just introduced in tk-core is available, leverage it if so, fallback on the caching per project/pipeline config/plugin id if not.
> 43294 cache sharing

- framework.py
Fix for data cleanup if tk-core version is older than v0.18.119 where `site_cache_location` was added:
* Check if `site_cache_location` is available before trying to use it.
> For #39289, fix for tk-core < 0.18.119

- python/shotgun_model/data_handler.py
- python/shotgun_model/data_handler_find.py
- python/shotgun_model/data_handler_nav.py
We're switching to tk-core's version, since the framework has required use of 0.18 for a while now and tk-core has the correct implementation.
> `log_timing` does not properly wrap methods resulting in messy tracebacks

- python/shotgun_model/shotgun_query_model.py
Fix for crashes when removing items in Nuke:
Use `takeRow` instead of `deleteRow` when removing items to prevent RuntimeError: Internal C++ object (ShotgunStandardItem) already deleted errors, the item being already garbage collected in some cases (e.g. in Nuke).
> For #38483, fix for deleting items.

- python/shotgun_model/shotgun_query_model.py
Brings out this fix as a separate ticket and PR so that it doesn't get stuck in a feature branch for too long: https://github.com/shotgunsoftware/tk-framework-shotgunutils/pull/82/files#diff-d442a3297316abbae14a00adf3457696R1034
This fixes an issue where the `data_refreshed` signal was always returning a `True` flag, thereby indicating that data had changed, effectively meaning we were generating many false positives.
> #47017 Fixes bug where data_refreshed always returns true

- python/external_config/configuration_state.py
Fixes a bug which was causing deletion of pipeline configurations to go un-noticed by the update detection. With this change, the hash representing the current state of the software entity + pipeline configuration entity is computed as the `updated_at` timestamps for all records in the software entity + all pipeline configurations belonging to projects which have not be archived. (this constraint is not not have an ever growing number of configurations to consider of the life cycle of a shotgun site).
> #46914 caching delete bug

- python/external_config/external_config_loader.py
Tweak to the behaviour of the `request_configurations()` method -- if called multiple times in rapid succession, only a single signal will be emitted. Any queued up or in-progress signals are basically discarded when `request_configurations()` is called.
> #47089 Adjustments to signal policy

- python/shotgun_model/data_handler_find.py
- python/shotgun_model/shotgun_query_model.py
During the hard refresh of a ShotgunQueryModel, the data handler's cache would be cleared out, and then the refresh process would request an update of the model's data. That call would fail, as it raised when no cache existed for the data handler. Instead, we now treat the missing cache kindly and just continue on with the update, which itself populates a fresh cache.
> SG-6836: Fixes a bug that manifested when a model hard_refresh was called

- python/external_config/config/config_base.py
- python/external_config/config/config_fallback.py
- python/external_config/config/config_invalid.py
- python/external_config/config/config_live.py
- python/external_config/config/config_remote.py
- python/external_config/config/factory.py
- python/external_config/errors.py
- python/external_config/external_config_loader.py
- python/external_config/scripts/external_runner.py
This is a reimplementation of how we track inaccessible configurations found when getting configs, and how those are reported to the caller. Instead of passing error messages to the caller, we now track invalid configurations as an "invalid" external configuration object with an enum status that can be used to know WHY the configuration is invalid.
Currently, we only have enums for CONFIGURATION_READY and CONFIGURATION_INACCESSIBLE, but this can be expanded in the future if required.
> SG-7486: Reimplements how inaccessible configurations are communicated.

- python/external_config/config/config_base.py
- python/external_config/config/config_fallback.py
- python/external_config/config/config_invalid.py
- python/external_config/config/config_live.py
- python/external_config/config/config_remote.py
- python/external_config/config/factory.py
- python/external_config/errors.py
- python/external_config/external_command.py
- python/external_config/external_config_loader.py
- python/external_config/scripts/external_runner.py
Previous to this change, if all PC entities pointed to configs on disk that weren't accessible from the host, no response would be sent to the web app requesting menu actions via WSS. Instead, we now thoroughly warn and use the fallback configuration.
> SG-7486: Handles inaccessible configs on disk gracefully.

- python/external_config/scripts/external_runner.py
This is in addition to the existing check to see if any top-level widgets exist. We've run into cases where the widgets still exist in memory post execution, but are not visible. In that situation, we should go ahead and shut down the QApplication and exit the external process normally.
> SG-3025: Closes the external process when the command finishes if no widgets are visible.

- python/external_config/config/config_base.py
- python/external_config/external_command.py
Before we spawn a subprocess to run an external command, we now set PYTHONPATH to include everything in sys.path. This ensures that we're importing Python modules predictably from subprocesses.
> SG-7531: Ensures that PYTHONPATH includes everything in sys.path

- python/external_config/config/config_base.py
- python/external_config/external_command.py
- python/external_config/scripts/external_runner.py
This addresses an issue where the PYTHONPATH changes defined in external_config prior to spawning external_runner subprocesses would leak into DCCs launched from the external_runner. This caused some compatibility issues with Python libraries, as we overrode what shipped with the DCC with what SGC has bundled. That was bad, obviously, so we're now cleaning up after ourselves once the external_runner process is running, but before we spawn any processes from it.
> SG-7531: QA fixes for PYTHONPATH handling when spawning subprocesses.

- python/shotgun_model/util.py
Toolkit expects the following code
from PySide2 import QtGui
i = QtGui.QStandardItem()
i.setData(1, 1)
print i.data(1)._class_
to print out <type 'int'>, but in the case of VRed it gives back <type 'long'>.
> This is a workaround for https://jira.autodesk.com/browse/SHOT-2806

- docs/shotgun_globals.rst
Updated example documentation, as it was using the incorrect method names.
> Fix for doc example on registering a task manager

- python/shotgun_model/util.py
Removes a six import that relied on six being installed (rather than using the copy shipped with python-api.)  Since six was already imported below, we can just drop this import.
> Fixes error when six is not installed

- python/external_config/config/config_base.py
- python/external_config/external_command.py
- tests/external_config/test_external_command.py
This will allow for tk-desktop2 (and other integrations, where necessary) to change the interpreter path associated with a command after it's been loaded from the cache. This is useful in situations where the interpreter path might have changed after the commands were cached to disk, such as in SG Create where the path changes during an update of the host application.
> VMR-2799: Adds a getter/setter for interpreter paths in external commands

- python/external_config/external_command_utils.py
Fixes an issue where loading an external config with an older code would blow up in the `external_config_utils`. This is because the external configs were updated to use the new OS detection routines from 0.19, but the config that may be using the code may have been older and didn't have that code. I didn't bring back the code as it originally was but instead followed the best practices that were put in the in the new `sgtk.util.is_*` methods from tk-core
> SG-15546: Fix for external command utils with older tk-core

- python/task_manager/background_task_manager.py
- python/task_manager/worker_thread.py
- tests/bg_task_manager/__init__.py
- tests/bg_task_manager/test_background_task_manager.py
- tests/python/base_test.py
The workfiles 2 app passes in a priotity for it's threads, unlike most of the rest of our code, so we didn't catch this until now.
In Python 2, comparing `int` and `NoneType` was possible, but it is not permitted in Python 3, so we're making sure that priorities are always numerical now.
> SG-13276: Fixed task priority sorting

- python/external_config/external_config_loader.py
- tests/external_config/test_external_config_loader.py
This pull request avoid this issue:
```
".../python/external_config/external_config_loader.py", line 169, in request_configurations
for task_id in self._task_ids.keys():
RuntimeError: dictionary changed size during iteration
```
The fix is pretty straight forward.
> Improve Python3 support

- python/external_config/config/config_base.py
- python/external_config/external_command.py
- python/external_config/scripts/external_runner.py
Send the currently used user to the external runner so it doesn't rely
on having to grab the current user at runtime.
With this change, someone who trigger multiple actions and logout won't
get login screens appearing at the moment the action get executed.
> Serialize the user with the external runner args

- python/external_config/config/config_base.py
- python/external_config/external_command.py
- python/external_config/scripts/external_runner.py
JIRA: SG-16456
Altering the PYTHONPATH variable can create multiple undesirable
side-effects if not done carefully.
This changes allow the user to launch two scripts in succession without
having Shotgun Create's python sys.path leaked inside of the second script's PYTHONPATH.
> Keep PYTHONPATH untouched while launching a script

- python/external_config/scripts/external_runner.py
This suppresses the libpng and imp deprecation warnings that are shown in the browser integration when using SG Create.
The imp warning is only logged when the script that is directly run in python has an imp import in it. Importing other modules from that script that contain imp import won't trigger the warning. However in this case the `external_runner.py` script is executed in a new Python instance, and contains an imp import in it, so we must suppress the warning.
> SG-18486 Now suppresses warnings that were popping up in browser integration.

- python/task_manager/background_task_manager.py
- python/task_manager/worker_thread.py
- tests/bg_task_manager/test_background_task_manager.py
Upgrading to PySide2 5.15 causes a deadlock when the WorkerThread's shut_down method is called.
In the past, we've had issues when mixing Qt and Python threading primitives and this is indeed what is going on here. The `WorkerThread` is a `QThread` but we use Python's `Mutex` and `Condition` classes to synchronize threads. I've simply modified the `WorkerThread` class to derive from Python's `Thread` class and now everything is fine.
I've had to modify the background manager test, as the last worker thread tried to shutdown the background manager. This meant that the worker ended up joining itself. Unfortunately, it appears Python threads can't join themselves, but Qt threads could, which means my change broke the test and introduced a side-effect.
Another subtle side-effect: the worker …
> SHOT-3508: Alternative PySide2 5.15.0 regression fix

- python/external_config/scripts/external_runner.py
Command callbacks should be called with `execute_old_style_command` and passed the entity data if the `suppports_multiple_selection` flag has a value. Whether it is True or False shouldn't make a difference.
> SG-19840 Fix for error when running Shotgun apps through Create

- python/shotgun_model/shotgun_query_model.py
* `removeRow` may cause the parent item to be deleted before we're done using it
* Use `takeRow` instead to ensure data is not deleted prematurely
* `takeRow` does not free the memory, but we own the objects and do not keep a reference to it, so garbage collection will free up the memory for us
> Fix 'Internal C++ object already deleted' when removing model rows

- python/external_config/external_command.py
This pull request fixes an issue where starting some DCCs from Shotgun Create fails because of the way DLLs are handled on Windows. Before this change, Shotgun Create starts external_runner.py (and then any external command) from his PWD, which is his own bin folder. The situation might end up problematic because of the way DLLs are loaded on Windows. In certain cases, the app will look at DLLs in the current directory instead of where you would expect it to load things and things end up failing in a very unexpected way.
The solution here is to always set the PWD to the home directory of the user. Why the home directory? For no reason, it's an arbitrary path that always exists and where you are unlikely to have DLLs that might break your tools. I am open to switching this to any other …
> SG-18781 - Set the cwd of the external_runner

- python/settings/user_settings.py
* QByteArray objects are not retrieved correctly after converting to str and pickling the value
* To handle QByteArray objects, add a param to the `store` method to allow storing the raw value (without converting to str and pickling)
For context, we want to add a splitter to the Loader2 App, and save/restore the splitter state in the settings (which is a QByteArray value): https://github.com/shotgunsoftware/tk-multi-loader2/pull/102
> Fix user settings to handle QByteArray values.

- README.md
- azure-pipelines.yml
- python/task_manager/worker_thread.py
> SG-32969 Test CI with Python 3.10

- python/shotgun_model/shotgun_hierarchy_model.py
- python/shotgun_model/shotgun_model.py
- python/shotgun_model/shotgun_query_model.py
When [shotgunpanel](https://github.com/shotgunsoftware/tk-multi-shotgunpanel) finds new items (notes, publishes, etc) it appends them to the end of the UI list. However, the default ordering should be the newest first. This PR attempts to fix that by specifying the index where to create new items when SG data arrives.
> SG-31932 Fix order when adding new items before caching

- docs/shotgun_hierarchy_model.rst
Documentation output is very similar, but some inherit methods from `ShotgunHierarchyModel` are not populated due to cross-referencing issue with Sphinx.
Left image is our current published site. Right image is the preview.
Discovered by tk-toolchain CI for Python 3.11
> SG-34509 SG-34514 Fix Sphinx issue with PySide6

- python/settings/user_settings.py
-  UserSettings - Error details: 'str' object has no attribute 'decode' 
Regression introduced in https://github.com/shotgunsoftware/tk-framework-shotgunutils/pull/168
> SG-40414 UserSettings - Error details: 'str' object has no attribute 'decode'
